apiVersion: apps/v1
kind: Deployment
metadata:
  name: authdb
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authdb
  template:
    metadata:
      labels:
        app: authdb
    spec:
      containers:
        - name: authdb
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "auth_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "12345"

---
apiVersion: v1
kind: Service
metadata:
  name: authdb
  namespace: app-namespace
spec:
  selector:
    app: authdb
  ports:
    - port: 5432
      targetPort: 5432