apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdb
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdb
  template:
    metadata:
      labels:
        app: orderdb
    spec:
      containers:
        - name: orderdb
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "order_service_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "12345"

---
apiVersion: v1
kind: Service
metadata:
  name: orderdb
  namespace: app-namespace
spec:
  selector:
    app: orderdb
  ports:
    - port: 5432
      targetPort: 5432